### ISSUE TITLE
axio method config should not be in .create() constructor

### ISSUE THREAD

**Issue by marco-ih-bcn** [anaresende/project-popcorn#16]
https://github.com/anaresende/project-popcorn/blob/adf2e02d7fbb0384e512985b7065136f1e674b87/api/api.js#L13

Please do not specify a method in the config constructor.
It does not make sense to set a method for all axios calls that will need to be overwritten every time.  with `axios.get()`, `axios.post()`

**Comment by anaresende** [comment]
We did it like this, because in this specific case, since we are using an external API, we only want to GET, but we fixed it already, and it's going to be in each api request in the next commit.

**Comment by marco-ih-bcn** [comment]
Close the issue when you are done
